USE [master]
GO
/****** Object:  Database [MVC2]    Script Date: 19-04-2020 21:10:53 ******/
CREATE DATABASE [MVC2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MVC2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MVC2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MVC2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MVC2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MVC2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MVC2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MVC2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MVC2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MVC2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MVC2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MVC2] SET ARITHABORT OFF 
GO
ALTER DATABASE [MVC2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MVC2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MVC2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MVC2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MVC2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MVC2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MVC2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MVC2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MVC2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MVC2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MVC2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MVC2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MVC2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MVC2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MVC2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MVC2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MVC2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MVC2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MVC2] SET  MULTI_USER 
GO
ALTER DATABASE [MVC2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MVC2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MVC2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MVC2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MVC2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MVC2] SET QUERY_STORE = OFF
GO
USE [MVC2]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 19-04-2020 21:10:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](20) NULL,
	[Age] [int] NULL,
	[Address] [varchar](20) NULL,
	[Gender] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LoginDetail]    Script Date: 19-04-2020 21:10:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoginDetail](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](30) NULL,
	[Password] [varchar](30) NULL,
	[Role] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Employee] ON 
GO
INSERT [dbo].[Employee] ([ID], [Name], [Age], [Address], [Gender]) VALUES (1, N'vijay', 20, N'delhi', N'M')
GO
INSERT [dbo].[Employee] ([ID], [Name], [Age], [Address], [Gender]) VALUES (2, N'abhishek', 21, N'allahabad', N'M')
GO
INSERT [dbo].[Employee] ([ID], [Name], [Age], [Address], [Gender]) VALUES (3, N'vishesh', 22, N'noida', N'M')
GO
INSERT [dbo].[Employee] ([ID], [Name], [Age], [Address], [Gender]) VALUES (4, N'sonal', 18, N'delhi', N'F')
GO
INSERT [dbo].[Employee] ([ID], [Name], [Age], [Address], [Gender]) VALUES (5, N'neha', 19, N'delhi', N'F')
GO
SET IDENTITY_INSERT [dbo].[Employee] OFF
GO
SET IDENTITY_INSERT [dbo].[LoginDetail] ON 
GO
INSERT [dbo].[LoginDetail] ([ID], [Name], [Password], [Role]) VALUES (1, N'sonal', N'sj123', N'Admin')
GO
INSERT [dbo].[LoginDetail] ([ID], [Name], [Password], [Role]) VALUES (2, N'neha', N'ng123', N'USER')
GO
SET IDENTITY_INSERT [dbo].[LoginDetail] OFF
GO
USE [master]
GO
ALTER DATABASE [MVC2] SET  READ_WRITE 
GO
